# **Secure and Private AI**

The following code was developed while I was taking part of the course ***Secure and Private AI*** by Andrew Trask. In case you want more information, go to *udacity.com*, where you can take the course.

## **1. Building a private dataset**

Developed during the course first lesson.

### **Info**

In this project, we want to take an existing database and automatically generate every possible parallel database to that original database. 

We'll iterate through the database and at each point we'll remove an element.

### **Setting up the environment**

In [0]:
!pip install syft
!pip install numpy

     |████████████████████████████████| 215kB 3.5MB/s 
     |████████████████████████████████| 256kB 59.6MB/s 
     |████████████████████████████████| 71kB 30.3MB/s 
     |████████████████████████████████| 204kB 62.0MB/s 
     |████████████████████████████████| 450kB 57.1MB/s 
     |████████████████████████████████| 1.4MB 58.4MB/s 
     |████████████████████████████████| 389kB 54.2MB/s 
     |████████████████████████████████| 51kB 27.8MB/s 
     |████████████████████████████████| 276kB 49.1MB/s 
     |████████████████████████████████| 122kB 52.4MB/s 
  Stored in directory: /root/.cache/pip/wheels/ad/9a/f4/3105b5209674ac77fcca7fede95184c62a95df0196888e0e76
  Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
Successfully built zstd pyyaml
  Found existing installation: msgpack 0.5.6
    Uninstalling msgpack-0.5.6:
      Successfully uninstalled msgpack-0.5.6
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
   

In [0]:
import torch

### **Creating the dataset**

In [0]:
num_entries = 500

db = torch.rand(num_entries) > 0.5
db

tensor([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
        0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
        1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,

### **Removing an item**

In [0]:
def get_parallel_db(db, remove_index): 
  
  return torch.cat((db[0:remove_index], db[remove_index+1:]))

In [0]:
get_parallel_db(db,2)[0:5]

tensor([0, 1, 1, 0, 1], dtype=torch.uint8)

### **Iterating through the dataset**

In [0]:
def get_parallel_dbs(db):
  parallel_dbs = list()

  for i in range(len(db)):
    pdb = get_parallel_db(db, i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs

In [0]:
pdbs = get_parallel_dbs(db)

In [0]:
pdbs

[tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
         1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
         0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
         0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
         1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
         1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
         1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
         0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
         0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
         0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
         1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
         0, 1, 0, 1, 1, 1, 1

### **Putting all together**

In [0]:
def create_db_and_parallels(num_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [0]:
db[0:5]

tensor([0, 0, 0, 0, 0], dtype=torch.uint8)

In [0]:
pdbs

[tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,

## **2. Evaluating the privacy**

Developed during the second lesson

### **Sensitivity function**

Sensitivity: maximum amount that the query changes when removing an individual from the database.

We created a database full of ones and zeros, so if we remove only one element the maximun difference must be 1.

In [0]:
def query(db):
  return db.sum()

In [0]:
def sensitivity(query, num_entries = 1000):
  max_distance = 0
  
  db, pdbs = create_db_and_parallels(num_entries)
  
  full_db_result = query(db)
  
  for pdb in pdbs:
    pdb_result = query(pdb)
   
    db_distance = torch.abs(pdb_result - full_db_result)  
   
    if (db_distance > max_distance):
      max_distance = db_distance
  
  return max_distance

In [0]:
sensitivity(query)

tensor(1)

### **L1 Sensitivity for threshold**

Here we'll follow the next steps:
 
*   Create the query function
*   Create 10 db of size 10
*   Query each db with a threshold of 5
*   Print the sensitivity 



In [0]:
def query(db, threshold = 5):
  return (db.sum() > threshold).float()

In [0]:
for i in range(10):
  print(sensitivity(query, num_entries=10))

0
tensor(1.)
0
0
0
0
0
tensor(1.)
0
0


### **Performing a Diffferencing Attack on row 10**

The goal of this section is to obtain row 10 value. For that, we'll do two queries (one computing the 10th row and another without). Then we'll compare them.

In [0]:
db, _ = create_db_and_parallels(100)

In [0]:
pdb = get_parallel_db(db, remove_index=10) # db without row10

In [0]:
db[10] # value we're trying to find

tensor(0, dtype=torch.uint8)

In [0]:
# differencing attack using sum query

sum(db)-sum(pdb)

tensor(0, dtype=torch.uint8)

In [0]:
# differencing attack using mean query

(sum(db).float()/len(db)) - (sum(pdb).float()/len(pdb))

tensor(-0.0057)

In [0]:
sum(db)

tensor(56, dtype=torch.uint8)

In [0]:
# differencing attack using threshold query

(sum(db).float() > 48) - (sum(pdb).float() > 48)

tensor(0, dtype=torch.uint8)

## **3. Local and Global Differencial Privacy**

### **Implementing Local Differential Privacy**

Let's picture the following situation. We have a group of people we want to suvey about a negative behaviour (let's say that is if they have stolen something). Of course some might refuse to answer.

Well, by using the next steps, we are able to protect the privacy of our subjects.
*   flip a coin 2 times
*   if the first coin flip is heads ,tell the truth
*   if it doesn't, answer according the second coind (yes for heads, no for tails)

Now, we a person answers, we have no way to tell if their answer is true or if it comes from the second coin (therefore we protect their privacy).

On top of that, we now that wathever the probability of stealing is, we're averaging it with a 50% prob. from the coins. This means that if the prob we have after our survey is 60%, the we now the real prob is 70%, because the averaging 70 and 50 we have 60.

However, the protection of our users has it costs. The greater privacy protection, the less accurate the results.

In [0]:
def query(db):
  true_result = torch.mean(db.float())
  
  first_coin_flip = (torch.rand(len(db)) > 0.5).float()
  second_coin_flip = (torch.rand(len(db)) > 0.5).float()
  
  augmented_database = db.float() * first_coin_flip + (1 - first_coin_flip) * second_coin_flip
  
  db_result = torch.mean(augmented_database.float()) * 2 - 0.5
  
  return db_result, true_result

Let's see how this noise affect our db depending on the number of entries it has.

In [0]:
db, pdbs = create_db_and_parallels(10)
priv_res , true_res = query(db)
print("With noise: " + str(priv_res))
print("Without noise: " + str(true_res))

With noise: tensor(0.7000)
Without noise: tensor(0.5000)


In [0]:
db, pdbs = create_db_and_parallels(100)
priv_res , true_res = query(db)
print("With noise: " + str(priv_res))
print("Without noise: " + str(true_res))

With noise: tensor(0.4600)
Without noise: tensor(0.4700)


In [0]:
db, pdbs = create_db_and_parallels(100000)
priv_res , true_res = query(db)
print("With noise: " + str(priv_res))
print("Without noise: " + str(true_res))

With noise: tensor(0.5013)
Without noise: tensor(0.4991)


When we add noise, we are corrupting our dataset. Howhever, the more datapoints we have, the more this noise will tend to average out.

### **Varying the amount of noise**

Now, we'll modify our query function to vary the chances of the first coin.

In [0]:
def query(db, percent):
  true_result = torch.mean(db.float())
  
  first_coin_flip = (torch.rand(len(db)) > percent).float()
  second_coin_flip = (torch.rand(len(db)) > 0.5).float()
  
  augmented_database = db.float() * first_coin_flip + (1 - first_coin_flip) * second_coin_flip
  
  sk_result = augmented_database.float().mean()
  
  db_result = ((sk_result/percent)-0.5)*percent/(1-percent)
  
  return db_result, true_result

In [0]:
db, pdbs = create_db_and_parallels(100)
priv_res , true_res = query(db, 0.2)
print("With noise: " + str(priv_res))
print("Without noise: " + str(true_res))

With noise: tensor(0.5875)
Without noise: tensor(0.5500)


In [0]:
db, pdbs = create_db_and_parallels(100)
priv_res , true_res = query(db,0.7)
print("With noise: " + str(priv_res))
print("Without noise: " + str(true_res))

With noise: tensor(0.5000)
Without noise: tensor(0.5300)


### **Global Differentially Privacy** 

The amount of noise we need to add to the output of a query depends on:
*   the type of noise (Gaussian/Laplacian)
*   the sensitivity of the query/function
*   the desired epsilon
*   the desired delta

For Laplacian noisse, delta is always 0 and we can choose the amount of noise using:


b = sensitivity(query)/epsilon

In [0]:
epsilon = 0.5 

The smaller we make this number (*epsilon*), the less information we're allowing to leak. This means we'll add more noise to our results.

In [0]:
import numpy as np

In [0]:
db, pdbs = create_db_and_parallels(100)

First, we'll do it for a sum query

In [0]:
def sum_query(db):
  return db.sum()

In [0]:
def laplacian_mechanism(db, query, sensitivity):
  
  beta = sensitivity/epsilon
  noise = torch.tensor(np.random.laplace(0, beta, 1))
  
  return query(db)+noise

In [0]:
laplacian_mechanism(db, sum_query, 1)

tensor([42.0475], dtype=torch.float64)

In [0]:
sum(db)  # real query

tensor(46, dtype=torch.uint8)

Now, we're doing it for a mean query

In [0]:
def mean_query(db):
  return torch.mean(db.float())

In [0]:
laplacian_mechanism(db, mean_query, 1/100)

tensor([0.4518], dtype=torch.float64)

In [0]:
mean_query(db)

tensor(0.4600)

## **4. Differential Privacy for Deep Learning**

In this section we'll imagine the following scenario. We work for a hospital and we have a db with a bunch of unlabeled images. Instead of labeling one by one we want to use a model to predict the labels. For this, that's what we'll do:
*  Ask 10 hospitals with labeled data to train the model
*  Use each of the trained model to predict labels
*  Perform a query to generate the true label (that will be the most repeated). After this, we'll add noise to protect the privacy
*  Retrain a new model with our labeled dataset

We'll skip the machine learning bit of it and asume that we have 10.000 training examples and 10 labels for each.

In [0]:
num_teachers = 10 #hospitals
num_examples = 10000
num_labels = 10

In [0]:
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int)

In [0]:
preds[0]

array([1, 1, 3, ..., 6, 8, 1])

In [0]:
new_labels =list()
for an_image in preds:
  
  label_counts = np.bincount(an_image, minlength=num_labels)
  
  epsilon = 0.1
  beta = 1/epsilon
  
  for i in range(len(label_counts)):
    label_counts[i] += np.random.laplace(0, beta, 1)
    
  new_label = np.argmax(label_counts)
  
  new_labels.append(new_label)

### **PATE Analysis**

In [0]:
!pip install syft

In [0]:
from syft.frameworks.torch.differential_privacy import pate

W0626 10:58:10.003853 140624334940032 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0-rc1.so'
W0626 10:58:10.019631 140624334940032 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
num_teachers, num_examples, num_labels = (100,100,10)
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int) #fake preds
indices = (np.random.rand(num_examples) * num_labels).astype(int) # true answers

In [0]:
data_dep_eps, data_ind_eps = pate.perform_analysis(teacher_preds=preds, true_indices=indices, noise_eps=0.1, delta=1e-5)
print("Data independent eps", data_ind_eps)
print("Data dependen eps", data_dep_eps)

TypeError: ignored

## **5. Federated Learning**

### **Introducing PySyft**

In [0]:
!pip install syft

     |████████████████████████████████| 215kB 2.7MB/s 
     |████████████████████████████████| 71kB 27.1MB/s 
     |████████████████████████████████| 1.4MB 44.0MB/s 
     |████████████████████████████████| 389kB 40.6MB/s 
     |████████████████████████████████| 204kB 40.3MB/s 
     |████████████████████████████████| 256kB 24.5MB/s 
     |████████████████████████████████| 450kB 39.7MB/s 
     |████████████████████████████████| 276kB 38.4MB/s 
     |████████████████████████████████| 51kB 20.6MB/s 
     |████████████████████████████████| 122kB 38.1MB/s 
  Stored in directory: /root/.cache/pip/wheels/ad/9a/f4/3105b5209674ac77fcca7fede95184c62a95df0196888e0e76
  Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
Successfully built zstd pyyaml
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Found existing installation: msgpack 0.5.6
    Uninstalling msgpack-0.5.6:
     

In [0]:
import torch as th

In [0]:
x = th.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [0]:
y = x + x
y

tensor([ 2,  4,  6,  8, 10])

In [0]:
import syft as sy

W0626 15:27:52.073005 139693122336640 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0-rc1.so'
W0626 15:27:52.096501 139693122336640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
hook = sy.TorchHook(th)

In [0]:
th.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

### **PySyft (Remote PyTorch)**

In Federated Learning we need to work in a number of parallel machines. Because of that, now will work with pointers instead of tensors.

In [0]:
bob = sy.VirtualWorker(hook, id="bob")

In [0]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5])

In [0]:
x = x.send(bob)
bob._objects

{44350842930: tensor([1, 2, 3, 4, 5])}

In [0]:
x.location

<VirtualWorker id:bob #objects:1>

In [0]:
x.owner

<VirtualWorker id:me #objects:0>

In [0]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [0]:
bob._objects

{}

### **Playing with remote tensors**

In [0]:
alice = sy.VirtualWorker(hook, id="alice")

In [0]:
x = th.tensor([1,2,3,4,5])

In [0]:
x_ptr = x.send(bob,alice)

In [0]:
x_ptr.get()

[tensor([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5])]

### **Remote arithmetic**

In [0]:
x = th.tensor([1,2,3]).send(bob)
y = th.tensor([1,1,1]).send(bob)

In [0]:
x
y
z = th.add(x,y)
z

(Wrapper)>[PointerTensor | me:94425236573 -> bob:56849816558]

### **Learn a simple linear model**

In [0]:
input = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad = True).send(bob)
target = th.tensor([[1.],[1],[0],[0]], requires_grad=True).send(bob)                          

In [0]:
weights = th.tensor([[0.],[0.]], requires_grad=True).send(bob)

In [0]:
for i in range(10):
  
  pred = input.mm(weights)
  
  loss = ((pred-target)**2).sum()
  
  loss.backward()
  
  weights.data.sub_(weights.grad*0.1)
  weights.grad *= 0
  
  print(loss.get().data)

tensor(2.)
tensor(0.5600)
tensor(0.2432)
tensor(0.1372)
tensor(0.0849)
tensor(0.0538)
tensor(0.0344)
tensor(0.0220)
tensor(0.0141)
tensor(0.0090)


### **Toy Federated Learning**

In [0]:
from torch import nn, optim
import torch as th

In [0]:
# A toy dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad = True)
target = th.tensor([[1.],[1],[0],[0]], requires_grad=True) 

In [0]:
#A toy model
model = nn.Linear(2,1)

In [0]:
opt = optim.SGD(params=model.parameters(), lr = 0.1)

In [0]:
def train(iterations=20):
  
  for i in range(iterations):
    opt.zero_grad()

    pred = model(data)
    loss = ((pred-target)**2).sum()

    loss.backward()

    opt.step()

    print(loss.data)
  

train()

tensor(7.1315)
tensor(1.5408)
tensor(0.7652)
tensor(0.4783)
tensor(0.3092)
tensor(0.2011)
tensor(0.1313)
tensor(0.0860)
tensor(0.0565)
tensor(0.0373)
tensor(0.0248)
tensor(0.0165)
tensor(0.0111)
tensor(0.0075)
tensor(0.0051)
tensor(0.0035)
tensor(0.0024)
tensor(0.0017)
tensor(0.0012)
tensor(0.0008)


Now we'll make this model federated by sending the data to bob and alice and training our model there.

In [0]:
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

data_alice = data[0:2].send(alice)
target_alice = target[0:2].send(alice)

In [0]:
datasets = [(data_bob,target_bob), (data_alice, target_alice)]

In [0]:
def train(iterations=20):
  
  model = nn.Linear(2,1)
  opt = optim.SGD(params=model.parameters(), lr = 0.1)
  
  for i in range(iterations):
    
    for _data, _target in datasets:
      
      #sending the model
      model = model.send(_data.location)
      
      #regular training
      opt.zero_grad()

      pred = model(_data)
      loss = ((pred-_target)**2).sum()

      loss.backward()

      opt.step()
      
      #returning the model
      model = model.get()

      print(loss.get())


train()

tensor(1.1048, requires_grad=True)
tensor(0.1448, requires_grad=True)
tensor(0.1146, requires_grad=True)
tensor(0.0953, requires_grad=True)
tensor(0.0793, requires_grad=True)
tensor(0.0660, requires_grad=True)
tensor(0.0550, requires_grad=True)
tensor(0.0457, requires_grad=True)
tensor(0.0381, requires_grad=True)
tensor(0.0317, requires_grad=True)
tensor(0.0264, requires_grad=True)
tensor(0.0219, requires_grad=True)
tensor(0.0183, requires_grad=True)
tensor(0.0152, requires_grad=True)
tensor(0.0127, requires_grad=True)
tensor(0.0105, requires_grad=True)
tensor(0.0088, requires_grad=True)
tensor(0.0073, requires_grad=True)
tensor(0.0061, requires_grad=True)
tensor(0.0051, requires_grad=True)
tensor(0.0042, requires_grad=True)
tensor(0.0035, requires_grad=True)
tensor(0.0029, requires_grad=True)
tensor(0.0024, requires_grad=True)
tensor(0.0020, requires_grad=True)
tensor(0.0017, requires_grad=True)
tensor(0.0014, requires_grad=True)
tensor(0.0012, requires_grad=True)
tensor(0.0010, requi

### **Advanced Remote Execution Tools**

In [0]:
bob.clear_objects()

<VirtualWorker id:bob #objects:0>

In [0]:
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,1,1]).send(bob)

In [0]:
x = x.send(alice)

In [0]:
bob._objects

{17852148297: tensor([1, 1, 1])}

In [0]:
alice._objects

{59233375406: (Wrapper)>[PointerTensor | alice:59233375406 -> bob:17852148297]}

In [0]:
y = x + x

In [0]:
y

(Wrapper)>[PointerTensor | me:94405961767 -> alice:18102857900]

In [0]:
bob._objects

{17852148297: tensor([1, 1, 1]), 62269451727: tensor([2, 2, 2])}

This way, we are creating a chain. We have data in bob's, pointers to that data in alice's and we have pointers to alice's ones.

We can protect the data by sending the pointers to two different middle women.

In [0]:
mary = sy.VirtualWorker(hook, id="mary")

In [0]:
x = th.tensor([2,2,2]).send(bob).send(alice)
y = th.tensor([2,1,2]).send(bob).send(mary)

In [0]:
z = x+y

TensorsNotCollocatedException: ignored

That leads to an errod because although both tensors are stored in bob's, alice and mary disagree (the pointers to the data aren't stored in the same machine).

### **PointerChain Operations**

This way we can move data from bob directly to alice.

In [0]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([5,5,5]).send(bob).send(alice)

In [0]:
bob._objects

{78413604435: tensor([5, 5, 5])}

In [0]:
alice._objects

{71696799926: (Wrapper)>[PointerTensor | alice:71696799926 -> bob:78413604435]}

In [0]:
x.remote_get()

(Wrapper)>[PointerTensor | me:76483131990 -> alice:71696799926]

In [0]:
bob._objects

{}

In [0]:
alice._objects

{71696799926: tensor([5, 5, 5])}

In [0]:
# we can also use
x.move(bob)

(Wrapper)>[PointerTensor | me:76483131990 -> bob:76483131990]

## **6. Securing Federated Learning**

### **Federated Learning with a Trusted Aggregator**

In [23]:
!pip install syft

     |████████████████████████████████| 215kB 6.8MB/s 
     |████████████████████████████████| 204kB 49.1MB/s 
     |████████████████████████████████| 71kB 26.0MB/s 
     |████████████████████████████████| 450kB 48.3MB/s 
     |████████████████████████████████| 1.4MB 43.9MB/s 
     |████████████████████████████████| 256kB 50.1MB/s 
     |████████████████████████████████| 389kB 41.5MB/s 
     |████████████████████████████████| 276kB 45.2MB/s 
     |████████████████████████████████| 51kB 20.5MB/s 
     |████████████████████████████████| 122kB 46.0MB/s 
  Stored in directory: /root/.cache/pip/wheels/ad/9a/f4/3105b5209674ac77fcca7fede95184c62a95df0196888e0e76
  Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
Successfully built zstd pyyaml
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Found existing installation: msgpack 0.5.6
    Uninstalling msgpack-0.5.6:
     

In [0]:
import syft as sy
import torch as th
hook = sy.TorchHook(th)
from torch import nn, optim

W0627 13:54:31.128722 140423213606784 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0-rc1.so'
W0627 13:54:31.142996 140423213606784 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secure_worker = sy.VirtualWorker(hook, id="secure_worker")

In [0]:
bob.add_workers([alice, secure_worker])
alice.add_workers([bob, secure_worker])
secure_worker.add_workers([bob, alice])

W0627 13:54:32.720081 140423213606784 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior
W0627 13:54:32.721551 140423213606784 base.py:628] Worker secure_worker already exists. Replacing old worker which could cause                     unexpected behavior
W0627 13:54:32.722666 140423213606784 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0627 13:54:32.723506 140423213606784 base.py:628] Worker secure_worker already exists. Replacing old worker which could cause                     unexpected behavior
W0627 13:54:32.724455 140423213606784 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0627 13:54:32.725634 140423213606784 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior


<VirtualWorker id:secure_worker #objects:0>

In [0]:
# A toy dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad = True)
target = th.tensor([[1.],[1],[0],[0]], requires_grad=True)


In [0]:
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

data_alice = data[2:].send(alice)
target_alice = target[2:].send(alice)

In [0]:
model = nn.Linear(2,1)

Now, we''ll have two different model that'll be sended to both workers.

In [0]:
bobs_model = model.copy().send(bob)
alices_model = model.copy().send(alice)

In [0]:
bobs_opt = optim.SGD(params=bobs_model.parameters(),lr=0.1)
alices_opt = optim.SGD(params=alices_model.parameters(),lr=0.1)

In [0]:
for i in range(10):

  # bob's model
  bobs_opt.zero_grad()
  bobs_pred = bobs_model(data_bob)
  bobs_loss = ((bobs_pred - target_bob)**2).sum()
  bobs_loss.backward()

  bobs_opt.step()
  bobs_loss = bobs_loss.get().data
  bobs_loss

  # alice's model
  alices_opt.zero_grad()
  alices_pred = alices_model(data_alice)
  alices_loss = ((alices_pred - target_alice)**2).sum()
  alices_loss.backward()

  alices_opt.step()
  alices_loss = alices_loss.get().data
  alices_loss

Now that we've trained both models separately, it's time to average them. For this, we'll send them to secure worker. 

In [0]:
alices_model.move(secure_worker)
bobs_model.move(secure_worker)

In [0]:
# here you should do model.weight.data.set_() but I keep having an error
model.weight.data = (((alices_model.weight.data + bobs_model.weight.data)/2).get())
model.bias.data = (((alices_model.bias.data + bobs_model.bias.data)/2).get())

### **Additive Secret Sharing**

Even this way (the one we did in the previous section), we need to trust a third party to see our raw data. 

We can modify this, by adding encription to our data. For that reason, we're going to use Additive Secret Sharing. We'll need the following functions.

In [0]:
import random

In [0]:
Q = 23740629843760239486723

In [0]:
def encrypt(x, n_shares=3):
  
  shares = list()
  
  for i in range(n_shares-1):
    shares.append(random.randint(0,Q))
    
  final_share = Q -(sum(shares)%Q) + x
  
  shares.append(final_share)
  
  return tuple(shares)

In [0]:
encrypt(5,3)

(14240640204254952100607, 22783298396949810508307, 10457321086315716364537)

In [0]:
def decrypt(shares):
  return (sum(shares)%Q)
  

In [0]:
decrypt(encrypt(4))

4

In [0]:
def add(a,b):
  
  c = list()
  
  assert(len(a) == len(b))
  
  for i in range(len(a)):
    c.append((a[i]+b[i])%Q)
    
  return tuple(c)

In [0]:
decrypt(add(encrypt(7),encrypt(7)))

14

We can also create other functions as subtraciont and multiplication

In [0]:
def subtract(a,b):
  
  c = list()
  
  assert(len(a) == len(b))
  
  for i in range(len(a)):
    c.append((a[i]-b[i])%Q)
    
  return tuple(c)

In [0]:
decrypt(subtract(encrypt(7),encrypt(2)))

5

In [0]:
# multiply encrypted umber by a known scalar
def multiply(a,scalar):
  
  c = list()
  
  for i in range(len(a)):
    c.append((a[i]*scalar)%Q)
    
  return tuple(c)

In [0]:
decrypt(multiply(encrypt(7),2))

14

### **Fixed Precision Encoding**

Our goal is to encode the weights by using the previous technique. However it only works with integer. FPE lets us do computation over decimal numbers using integers.

In [0]:
BASE = 10
PRECISION = 4
Q = 23740629843760239486723

In [0]:
def encode(x_dec):
  return int(x_dec*(BASE**PRECISION))% Q

In [0]:
def decode(x_fp):
  return (x_fp if x_fp <= Q/2 else x_fp-Q) / BASE**PRECISION

In [0]:
decode(encode(0.5))

0.5

### **Fixed Precision in PySyft**

In [0]:
bob = bob.clear_objects()
alice = alice.clear_objects()
secure_worker = secure_worker.clear_objects()

In [0]:
x = th.tensor([1,2,3,4,5])

In [0]:
x = x.share(bob,alice,secure_worker)
x

(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:16564879343 -> bob:8196139741]
	-> (Wrapper)>[PointerTensor | me:68102753621 -> alice:83916737827]
	-> (Wrapper)>[PointerTensor | me:92935346880 -> secure_worker:59895894078]
	*crypto provider: me*

In [0]:
bob._objects

{8196139741: tensor([3180144277271009586, 3095836909958152134, 3918868126591434552,
         2121681609746945176, 2386369850837645924])}

In [0]:
y = x + x

In [0]:
y.get()

tensor([ 2,  4,  6,  8, 10])

In [0]:
x = th.tensor([0.1,0.2,0.3,0.4,0.5])
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])

In [0]:
x = x.fix_prec()
x

(Wrapper)>FixedPrecisionTensor>tensor([100, 200, 300, 400, 500])

In [0]:
x = x.float_prec()
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])

## **7. Encrypted Deep Learning**

### **Encrypted computation in PySyft**

In [24]:
import syft as sy
import torch as th
hook = sy.TorchHook(th)
from torch import nn, optim

W0701 15:24:14.065461 139722714326912 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0701 15:24:14.090709 139722714326912 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secure_worker = sy.VirtualWorker(hook, id="secure_worker")

In [0]:
x = th.tensor([1,2,3,4])
y = th.tensor([2,-1,1,0])

In [0]:
x = x.share(bob, alice, crypto_provider=secure_worker)

In [0]:
y = y.share(bob, alice, crypto_provider=secure_worker)

In [0]:
z = x + y
z.get()

tensor([3, 1, 4, 4])

In [0]:
z = x - y
z.get()

tensor([-1,  3,  2,  4])

In [0]:
z = x * y
z.get()

tensor([ 2, -2,  3,  0])

In [0]:
z = x > y
z.get()

tensor([0, 1, 1, 1])

In [0]:
z = x == y
z.get()

tensor([0, 0, 0, 0])

### **Building an Encrypted Database**

In [0]:
import string
import torch as th

In [0]:
char2index = {}
index2char = {}

In [0]:
for i,char in enumerate(' ' + string.ascii_lowercase + '0123456789' + string.punctuation):
  char2index[char] = i
  index2char[i] = char

In [0]:
  str_input = "Hello"
  max_len = 8
  

In [0]:
def string2values(str_input, max_len=8):

  str_input = str_input[:max_len].lower()
  
  if(len(str_input)<max_len):
    str_input = str_input + " , " * (max_len-len(str_input))
    
  values = list()
  for char in str_input:
    values.append(char2index[char])
    
  return th.tensor(values).long()


def values2string(input_values):
  s = ""
  for value in input_values:
    s += int2char[int(value)]
  return s

In [7]:
string2values(str_input)

tensor([ 8,  5, 12, 12, 15,  0, 48,  0,  0, 48,  0,  0, 48,  0])

In [0]:
def one_hot(index, length):
  vect = th.zeros(length).long()
  vect[index] = 1
  return vect

In [9]:
one_hot(3,5)

tensor([0, 0, 0, 1, 0])

In [0]:
def string2one_hot_matrix(str_input, max_len=8):

  str_input = str_input[:max_len].lower()
  
  if(len(str_input)<max_len):
    str_input = str_input + " , " * (max_len-len(str_input))
    
  char_vectors = list()
  for char in str_input:
    char_v = one_hot(char2index[char], len(index2char)).unsqueeze(0)
    char_vectors.append(char_v)
    
  return th.cat(char_vectors, dim=0)

In [15]:
matrix = string2one_hot_matrix("Hello")
matrix

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 

We can check if two encrypted keys match by doing the following:

In [0]:
str_a = string2one_hot_matrix("Helll")
str_b = string2one_hot_matrix("Hello")

In [58]:
# returns 1 when both strings are the same
def strings_equal(str_a, str_b):

  if len(str_a) == len(str_b):
    vect = (str_a * str_b).sum(1)

    x = vect[0]

    for i in range(vect.shape[0]-1):
      x = x * vect[i+1]
  else:
    x = th.tensor(0)

  return x

strings_equal(str_a,str_b)

tensor(0)

In [0]:
class EncryptedDB():
  
  def __init__(self, *owners, max_key_len=8,max_val_len=8):
    self.max_key_len = max_key_len
    self.max_val_len = max_val_len
  
    # We'll encode the keys with one_hot_matrix and the data with string2values.
    self.keys = list()
    self.values = list()
    self.owners = owners

    
    
  def add_entry(self, key, value):
    key = string2one_hot_matrix(key)
    key = key.share(*self.owners)
    self.values.append(key)
    
    value = string2values(value, max_len=self.max_val_len)
    value = value.share(*self.owners)
    self.values.append(value)
        
    
  
  def query(self, query_str):
    query_matrix = string2one_hot_matrix(query_str)
    query_matrix = query_matrix.share(*self.owners)

    key_matches = list()
    
    for key in self.keys:
      
      key_match = strings_equal(key, query_matrix)
      key_matches.append(key_match)

    result = self.values[0] * key_matches[0]

    for i in range(len(self.values)-1):
      result += self.values[i+1] + key_matches[i+1]
      
    result = result.get()

    return values2string(result).replace(".","")

In [0]:
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secure_worker = sy.VirtualWorker(hook, id="secure_worker")

In [0]:
db = EncryptedDB(bob,alice,secure_worker,max_val_len=256)

db.add_entry("key1", "value1")
db.add_entry("key2", "value2")
db.add_entry("key3", "value3")
db.add_entry("key4", "value4")

db.query("key1")

### **Encrypted Deep Learning in PyTorch**

First we'll train a regular model

In [0]:
from torch import nn, optim
import torch.nn.functional as F

#Toy dataset
data = th.tensor([[0,0],[0,1],[1,0],[1,1.]], requires_grad=True)
target = th.tensor([[0],[0],[1],[1.]], requires_grad=True)

class Net(nn.Module):
  def __init__(self):
    super(Net,self).__init__()
    self.fc1 = nn.Linear(2,20)
    self.fc2 = nn.Linear(20,1)
    
  def forward(self,x):
    x = self.fc1(x)
    x = F.relu(x)
    x = self.fc2(x)
    return x
  
model =  Net()

def train():
  
  opt = optim.SGD(params=model.parameters(),lr=0.1)
  for i in range(20):
    
    opt.zero_grad()
    pred = model(data)
    loss = ((pred-target)**2).sum()
    loss.backward()
    opt.step()
    print(loss.data)
    
    
train()

tensor(1.5224)
tensor(5.4030)
tensor(19.5920)
tensor(3.5385)
tensor(0.9767)
tensor(0.8976)
tensor(0.8505)
tensor(0.7986)
tensor(0.7350)
tensor(0.6619)
tensor(0.5810)
tensor(0.4948)
tensor(0.4105)
tensor(0.3396)
tensor(0.2667)
tensor(0.2072)
tensor(0.1620)
tensor(0.1242)
tensor(0.0963)
tensor(0.0758)


In [0]:
model(data)
# it's suposed to predict 0,0,1,1

tensor([[ 0.1787],
        [-0.0091],
        [ 0.9044],
        [ 0.8731]], grad_fn=<AddmmBackward>)

Now, we'll encrypt both model and data.

In [0]:
encrypted_model = model.fix_precision().share(alice, bob, crypto_provider=secure_worker)

In [0]:
#just checking that it is indeed encrypted
list(encrypted_model.parameters())

[Parameter containing:
 Parameter>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
 	-> (Wrapper)>[PointerTensor | me:61526291620 -> alice:99966357011]
 	-> (Wrapper)>[PointerTensor | me:91775101613 -> bob:99043759602]
 	*crypto provider: secure_worker*, Parameter containing:
 Parameter>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
 	-> (Wrapper)>[PointerTensor | me:81270836623 -> alice:70833606441]
 	-> (Wrapper)>[PointerTensor | me:15704866925 -> bob:84054783600]
 	*crypto provider: secure_worker*, Parameter containing:
 Parameter>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
 	-> (Wrapper)>[PointerTensor | me:89406463235 -> alice:11130594071]
 	-> (Wrapper)>[PointerTensor | me:73475118996 -> bob:74594146332]
 	*crypto provider: secure_worker*, Parameter containing:
 Parameter>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
 	-> (Wrapper)>[PointerTensor | me:71261363168 -> alice:38937786591]
 	-> (Wrapper)>[PointerTensor | me:21461818858 -> bob:93208156

In [0]:
encrypted_data = data.fix_precision().share(alice, bob, crypto_provider=secure_worker)

In [0]:
encrypted_data

(Wrapper)>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:30947426895 -> alice:92302330790]
	-> (Wrapper)>[PointerTensor | me:79820632789 -> bob:9951067081]
	*crypto provider: secure_worker*

In [0]:
encrypted_prediction = encrypted_model(encrypted_data)

In [0]:
encrypted_prediction.get().float_precision()

tensor([[ 0.1800],
        [-0.0080],
        [ 0.9050],
        [ 0.8730]])

### **Encrypted Deep Learning in Keras**

Now we'll reproduce the previous section in Keras

In [0]:
from __future__ import print_function
import tensorflow.keras as keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, AveragePooling2D
from tensorflow.keras.layers import Activation

batch_size = 128
num_classes = 10
epochs = 2

img_rows, img_cols = 28, 28

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols,1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()

model.add(Conv2D(10, (3,3), input_shape=input_shape))
model.add(AveragePooling2D((2,2)))
model.add(Activation('relu'))
model.add(Conv2D(32, (3,3)))
model.add(AveragePooling2D((2,2)))
model.add(Activation('relu'))
model.add(Conv2D(64, (3,3)))
model.add(AveragePooling2D((2,2)))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
             optimizer=keras.optimizers.Adadelta(),
             metrics=['accuracy'])

model.fit(x_train, y_train, batch_size = batch_size,
          epochs=epochs, verbose=1, validation_data=(x_test,y_test))
score = model.evaluate(x_test,y_test,verbose=0)
print('Test loss', score[0])
print('Test accuracy', score[1])

11493376/11490434 [==============================] - 0s 0us/step


W0628 14:20:18.470101 140035515029376 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Train on 60000 samples, validate on 10000 samples
Epoch 1/2
60000/60000 [==============================] - 6s 108us/sample - loss: 2.3030 - acc: 0.1044 - val_loss: 2.3024 - val_acc: 0.1038
Epoch 2/2
60000/60000 [==============================] - 4s 60us/sample - loss: 2.3015 - acc: 0.1095 - val_loss: 2.3009 - val_acc: 0.1116
Test loss 2.30091893081665
Test accuracy 0.1116


In [0]:
model.save('short-conv-mnist.h5')

This time we'll do a keras hook.

In [0]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import AveragePooling2D, Conv2D, Dense, Flatten, ReLU, Activation

import syft as sy
hook = sy.KerasHook(tf.keras)

In [0]:
# Model
num_classes = 10
input_shape = (1,28,28,1)

model = Sequential()

model.add(Conv2D(10, (3,3), batch_input_shape=input_shape))
model.add(AveragePooling2D((2,2)))
model.add(Activation('relu'))
model.add(Conv2D(32, (3,3)))
model.add(AveragePooling2D((2,2)))
model.add(Activation('relu'))
model.add(Conv2D(64, (3,3)))
model.add(AveragePooling2D((2,2)))
model.add(Activation('relu'))
model.add(Flatten())
model.add(Dense(num_classes, activation="softmax"))

# loading pre-trained weights
pre_trained_weights = 'short-conv-mnist.h5'
model.load_weights(pre_trained_weights)

In [0]:
AUTO = True

alice = sy.TFEWorker(host='localhost:4000', auto_managed=AUTO)
bob = sy.TFEWorker(host='localhost:4001', auto_managed=AUTO)
carol = sy.TFEWorker(host='localhost:4002', auto_managed=AUTO)

In [0]:
model.share(alice, bob, carol)

In [0]:
model.serve(num_requests=3)

And that should be enough to start our server. If you want to check how the clients work, go to *https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/* and click on Part13 to follow the full tutorial.